name: planai
description: A Workout Generator App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: null
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mockito: ^5.4.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/gen/
  line_length: 200
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/loading_pack/
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans_ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/OpenSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/OpenSans_Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/OpenSans_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/OpenSans_Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_LightItalic.ttf
          style: italic
          weight: 300
